services:
  api:
    build: .
    container_name: LedgerFlow_api

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - /app/.venv

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/leadgerflow

    depends_on:
      - db
      - redis

  db:
    image: postgres:17

    container_name: postgres_LedgerFlow

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leadgerflow

    ports:
      - "5433:5432"

    volumes:
      - postgres_LedgerFlow_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: ledgerflow_redis

    restart: always

    ports:
      - "6379:6379"

  celery:
    build: .

    container_name: ledgerflow_celery

    command: uv run celery -A app.workers.celery_app:celery worker --loglevel=info

    volumes:
      - .:/app
      - /app/.venv

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/leadgerflow

    depends_on:
      - db
      - redis

volumes:
  postgres_LedgerFlow_data: