"""add foreign key categoria

Revision ID: 0fd14954723d
Revises: 2bb9073cf38d
Create Date: 2026-08-01 03:13:41.036411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fd14954723d"
down_revision: Union[str, Sequence[str], None] = "2bb9073cf38d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transacoes", sa.Column("categoria_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transacoes", "categorias", ["categoria_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transacoes_categoria_id_fkey", "transacoes", type_="foreignkey")
    op.drop_column("transacoes", "categoria_id")
    op.drop_table("categorias")
    # ### end Alembic commands ###
